
DROP TABLE IF EXISTS video_games.t_user CASCADE;



CREATE TABLE IF NOT EXISTS video_games.t_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_username VARCHAR NOT NULL UNIQUE,
    c_password VARCHAR NOT NULL
);


DROP TABLE IF EXISTS video_games.t_user_authority CASCADE;

CREATE TABLE IF NOT EXISTS video_games.t_user_authority
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user     INT     NOT NULL REFERENCES video_games.t_user (id),
    c_authority VARCHAR NOT NULL
);

DROP TABLE IF EXISTS video_games.t_deactivated_token;

CREATE TABLE IF NOT EXISTS video_games.t_deactivated_token
(
    id           UUID PRIMARY KEY,
    c_keep_until TIMESTAMP NOT NULL CHECK ( c_keep_until > now() )
);

insert into video_games.t_user (c_username,c_password) values ('kirill','$2a$10$Pt3w/uIbVfzA61TlHx3A/O12K/9sz60NKgi.DvbzOwDRZQEMT0/4u');
insert into video_games.t_user_authority (id_user,c_authority) values (1,'ROLE_ADMIN');
